### ISSUE TITLE
Versão do CodeIgniter

### ISSUE THREAD

**Issue by alansystem** [visaotec/SystemCar#2]
Algum motivo específico por utilizar a versão 1.0 do CodeIgniter? Afinal já está na 4, porém eu sugiro pelo menos a versão 3 já que a versão 4 mudou muito a estrutura.

**Comment by visaotec** [comment]
Olá, versão CodeIgniter 3.1.7 referente ao CodeIgniter só mudou o jeito de programas, mas a funcionalidade é a mesma
